usage_repo: https://github.com/absalon-james/usage.git
usage_version: 208508c3185c338a9776393b12c8f7907bb6c476

usage_config_dir: /etc/usage
usage_reports_dir: /etc/usage/reports

openrc_os_username: admin
openrc_os_tenant_name: admin
