usage_repo: https://github.com/rackerlabs/openstack-usage-report.git
usage_version: eb4c5e513e99a337702384aa21e2fe0787b71d49

usage_config_dir: /etc/usage
usage_reports_dir: /etc/usage/reports
usage_licensing_reports_dir: /etc/usage/licensing

openrc_os_username: admin
openrc_os_tenant_name: admin
